### ISSUE TITLE
Support for URDF Import

### ISSUE THREAD

**Issue by drashutoshspace** [denisgriaznov/CustomMuJoCoEnviromentForRL#3]
Hy there. 
First of all thank you for your support. I am new in mujoco and it's really very hard to find the tutorials regarding this. 

I am having a URDF model of a quadrupled robot. What are the best way to implement it using your repo. 

Can we use URDF directly or may we convert it to xml. 
Your suggestions will be very helpful.

**Comment by denisgriaznov** [comment]
I would suggest taking a look at this discussion:
https://github.com/google-deepmind/mujoco/issues/273
As far as I understand, MuJoCo supports this format with some caveats. It might be a good idea to try loading your URDF file into the model testing first to make sure everything is correct.

**Comment by drashutoshspace** [comment]
Hyy 
Thanks for your reply 
I will have a look
